services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: kovix
      POSTGRES_PASSWORD: kovix_pass
      POSTGRES_DB: kovix_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://kovix:kovix_pass@db:5432/kovix_db?schema=public
      JWT_SECRET: kovix_super_secret_cambia_esto_123
      WEB_ORIGIN: http://localhost:3000
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: 123456
      PORT: 4000
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID:-}
      FIREBASE_CLIENT_EMAIL: ${FIREBASE_CLIENT_EMAIL:-}
      FIREBASE_PRIVATE_KEY: ${FIREBASE_PRIVATE_KEY:-}

  web:
    build: ./web
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:4000

volumes:
  pgdata:
